document.write('<html data-wf-page="5fc7b229b9e4cb0449f8c59e" data-wf-site="5fc7b228ac2d36009331902f">');
document.write('<head>');
document.write('  <meta charset="utf-8">');
document.write('  <title>Crush 19</title>');
document.write('  <meta property="og:type" content="website">');
document.write('  <meta content="summary_large_image" name="twitter:card">');
document.write('  <meta content="width=device-width, initial-scale=1" name="viewport">');
document.write('  <link href="css/normalize.css" rel="stylesheet" type="text/css">');
document.write('  <link href="css/flow.css" rel="stylesheet" type="text/css">');
document.write('  <link href="css/crush19.css" rel="stylesheet" type="text/css">');
document.write('  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>');
document.write('  <script type="text/javascript">WebFont.load({  google: {    families: ["Inter:100,200,300,regular,500,600,700,800,900"]  }});</script>');
document.write('  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->');
document.write('  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>');
document.write('  <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">');
document.write('  <link href="images/webclip.png" rel="apple-touch-icon">');
document.write('</head>');
document.write('<body>');
document.write('  <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="fixed-nav w-nav">');
document.write('    <div class="container nav-container w-container">');
document.write('      <a href="index.html" aria-current="page" class="brand w-nav-brand w--current"><img src="images/New-Project-3.png" width="88" alt="" class="nav-logo"></a>');
document.write('      <nav role="navigation" class="nav-menu w-nav-menu">');
document.write('        <a href="login.html" class="nav-link w-inline-block">');
document.write('          <div class="nav-link-text">Login</div>');
document.write('        </a>');
document.write('        <a href="chat.html" class="nav-link w-inline-block">');
document.write('          <div class="nav-link-text">Chat</div>');
document.write('        </a>');
document.write('        <a href="parks.html" class="nav-link w-inline-block">');
document.write('          <div class="nav-link-text">Parks</div>');
document.write('        </a>');
document.write('        <a href="swipe.html" class="nav-link w-inline-block">');
document.write('          <div class="nav-link-text">Swipe</div>');
document.write('        </a>');
document.write('        <a href="covidstats.html" class="nav-link-2 w-nav-link">Covid Stats</a>');
document.write('      </nav>');
document.write('      <div class="menu-button w-nav-button"><img src="images/menu-icon-white.svg" loading="lazy" alt=""></div>');
document.write('    </div>');
document.write('    <div class="nav-gradient-container">');
document.write('      <div class="gradient-line thin"></div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="section-hero">');
document.write('    <div class="container">');
document.write('      <div class="text-center">');
document.write('        <h1 class="hero-text"><span class="text-gradient-1">Crush-19 </span></h1>');
document.write('        <h1 class="hero-text"><span class="text-gradient-2">The Pandemic<br>Dating app</span></h1>');
document.write('        <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="fixed-nav w-nav">');
document.write('          <div class="container nav-container w-container">');
document.write('            <a href="index.html" aria-current="page" class="brand w-nav-brand w--current"><img src="images/New-Project-3.png" width="88" alt="" class="nav-logo"></a>');
document.write('            <nav role="navigation" class="nav-menu w-nav-menu">');
document.write('              <a href="login.html" class="nav-link w-inline-block">');
document.write('                <div class="nav-link-text">Login</div>');
document.write('              </a>');
document.write('              <a href="chat.html" class="nav-link w-inline-block">');
document.write('                <div class="nav-link-text">Chat</div>');
document.write('              </a>');
document.write('              <a href="parks.html" class="nav-link w-inline-block">');
document.write('                <div class="nav-link-text">Parks</div>');
document.write('              </a>');
document.write('              <a href="swipe.html" class="nav-link w-inline-block">');
document.write('                <div class="nav-link-text">Swipe</div>');
document.write('              </a>');
document.write('              <a href="covidstats.html" class="nav-link-2 w-nav-link">Covid Stats</a>');
document.write('            </nav>');
document.write('            <div class="menu-button w-nav-button"><img src="images/menu-icon-white.svg" loading="lazy" alt=""></div>');
document.write('          </div>');
document.write('          <div class="nav-gradient-container">');
document.write('            <div class="gradient-line thin"></div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('      <div class="small-container">');
document.write('        <div class="text-center">');
document.write('          <div class="text-holder">');
document.write('            <h6 class="text-display">When sliding into DMs can land you in quarantine. We bring you a safer, user friendly,<br> dating experience in the world of a pandemic. </h6>');
document.write('          </div>');
document.write('        </div>');
document.write('        <div data-w-id="3d8609da-3448-387d-1e0e-10521ed65395" class="hero-product-demo">');
document.write('          <div class="product-macbookholder"><img src="images/macbook2x.png" loading="lazy" sizes="(max-width: 479px) 92vw, (max-width: 767px) 95vw, (max-width: 991px) 96vw, (max-width: 1279px) 77vw, (max-width: 1439px) 992px, 1120px" srcset="images/macbook2x-p-500.png 500w, images/macbook2x-p-800.png 800w, images/macbook2x-p-1080.png 1080w, images/macbook2x-p-1600.png 1600w, images/macbook2x.png 1792w" alt="">');
document.write('            <div class="product-icons-background"></div>');
document.write('          </div>');
document.write('          <div class="product-demo-sticky">');
document.write('            <div class="product-image-container">');
document.write('              <div class="product-container desktop"><img src="images/New-Project-4.png" loading="lazy" sizes="(max-width: 479px) 77vw, (max-width: 767px) 79vw, (max-width: 991px) 80vw, (max-width: 1279px) 58vw, (max-width: 1439px) 772px, 880px" srcset="images/New-Project-4.png 500w, images/New-Project-4.png 800w, images/New-Project-4.png 972w" alt="" class="product-image">');
document.write('                <a href="#" class="play-icon-holder w-inline-block w-lightbox"><img src="images/play-icon.svg" loading="lazy" alt="" class="play-icon-image">');
document.write('                  <script type="application/json" class="w-json">{');
document.write('  "items": [');
document.write('    {');
document.write('      "type": "video",');
document.write('      "originalUrl": "https://youtu.be/f6473OHF5zk",');
document.write('      "url": "https://youtube.com/watch?v=f6473OHF5zk",');
document.write('      "html": "<iframe class=\\"embedly-embed\\" src=\\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Ff6473OHF5zk%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Df6473OHF5zk&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Ff6473OHF5zk%2Fhqdefault.jpg&key=96f1f04c5f4143bcb0f2e68c87d65feb&type=text%2Fhtml&schema=youtube\\" width=\\"940\\" height=\\"528\\" scrolling=\\"no\\" title=\\"YouTube embed\\" frameborder=\\"0\\" allow=\\"autoplay; fullscreen\\" allowfullscreen=\\"true\\"></iframe>",');
document.write('      "thumbnailUrl": "https://i.ytimg.com/vi/f6473OHF5zk/hqdefault.jpg",');
document.write('      "width": 940,');
document.write('      "height": 528');
document.write('    }');
document.write('  ]');
document.write('}</script>');
document.write('                </a>');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="section">');
document.write('    <div class="container">');
document.write('      <div class="small-container">');
document.write('        <div class="text-center">');
document.write('          <h3>No installation </h3>');
document.write('          <p class="grey-text">Simply log into your account, put up your best pics, information about yourself, location. <br>Then check out the local singles you want to meet.</p>');
document.write('        </div>');
document.write('      </div>');
document.write('      <div class="horizontal-line"></div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="section">');
document.write('    <div class="container">');
document.write('      <div class="text-center">');
document.write('        <h2>Just say 💬 it</h2>');
document.write('        <div class="text-container">');
document.write('          <p class="grey-text">&quot; It&#x27;s not a date, we&#x27;re just agreeing to eat at the same table&quot;</p>');
document.write('        </div>');
document.write('      </div>');
document.write('      <div data-duration-in="300" data-duration-out="100" class="tabs w-tabs">');
document.write('        <div class="tabs-menu w-tab-menu">');
document.write('          <a data-w-tab="Tab 1" class="tab-link w-inline-block w-tab-link w--current">');
document.write('            <div class="tab-icon-holder">');
document.write('              <div class="tab-icon-gradient"></div><img src="images/pngwing-4.png" loading="lazy" alt="" class="tab-icon">');
document.write('            </div>');
document.write('            <h4 class="tab-title">Fast and easy</h4>');
document.write('            <p class="tab-description">Stop looking at happy couples on instagram. Find a match in your area. In the comfort of your home. While keeping safe during a pandemic.</p>');
document.write('          </a>');
document.write('          <a data-w-tab="Tab 2" class="tab-link w-inline-block w-tab-link">');
document.write('            <div class="tab-icon-holder">');
document.write('              <div class="tab-icon-gradient"></div><img src="images/pngwing-6.png" loading="lazy" alt="" class="tab-icon">');
document.write('            </div>');
document.write('            <h4 class="tab-title">Chat Directly</h4>');
document.write('            <p class="tab-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pharetra hendrerit placerat. Nunc dictum nunc fermentum leo blandit porta.</p>');
document.write('          </a>');
document.write('          <a data-w-tab="Tab 3" class="tab-link w-inline-block w-tab-link">');
document.write('            <h4 class="tab-title">Setup Dates</h4>');
document.write('            <p class="tab-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pharetra hendrerit placerat. Nunc dictum nunc fermentum leo blandit porta.</p>');
document.write('            <div class="tab-icon-holder">');
document.write('              <div class="tab-icon-gradient"></div><img src="images/pngwing-5.png" loading="lazy" alt="" class="tab-icon">');
document.write('            </div>');
document.write('          </a>');
document.write('          <a data-w-tab="Tab 4" class="tab-link w-inline-block w-tab-link">');
document.write('            <div class="tab-icon-holder">');
document.write('              <div class="tab-icon-gradient"></div><img src="images/pngwing-7.png" loading="lazy" height="55" alt="" class="tab-icon">');
document.write('            </div>');
document.write('            <h4 class="tab-title">Local Covid Info</h4>');
document.write('            <p class="tab-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pharetra hendrerit placerat. Nunc dictum nunc fermentum leo blandit porta.</p>');
document.write('          </a>');
document.write('        </div>');
document.write('        <div class="tab-content w-tab-content">');
document.write('          <div data-w-tab="Tab 1" class="tab-pane w-tab-pane w--tab-active"><img src="images/pngwing-8.png" loading="lazy" alt=""></div>');
document.write('  ');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="section section-grey">');
document.write('    <div class="container">');
document.write('      <h2>Make your Dating Life Simpler and Safer</h2>');
document.write('      <div class="text-container">');
document.write('        <p class="grey-text">“What are this blind dates?&#x27; he asked curiously .<br>&#x27;An old American institution of mismating.”<br>― <strong>Rona Jaffe</strong>.</p>');
document.write('      </div>');
document.write('      <div class="w-layout-grid feature-grid gap-30">');
document.write('        <a id="w-node-e79ddfb4d30e-49f8c59e" href="#" class="card-item fadein-into-view change-color w-inline-block">');
document.write('          <div class="card-item-content"><img src="images/aurora-icon.svg" loading="lazy" alt="">');
document.write('            <h4>Built with saftey in mind</h4>');
document.write('          </div>');
document.write('          <div class="card-item-gradient"></div>');
document.write('        </a>');
document.write('        <a id="w-node-dd08978e7111-49f8c59e" href="#" class="card-item fadein-into-view change-color w-inline-block">');
document.write('          <div class="card-item-content"><img src="images/direction-icon.svg" loading="lazy" alt="">');
document.write('            <h4>Match with people anywhere</h4>');
document.write('          </div>');
document.write('          <div class="card-item-gradient"></div>');
document.write('        </a>');
document.write('        <a id="w-node-28d94f9e33a4-49f8c59e" href="#" class="card-item fadein-into-view change-color w-inline-block">');
document.write('          <div class="card-item-content">');
document.write('            <h4>Chat and find book dates</h4>');
document.write('          </div>');
document.write('          <div class="card-item-gradient gradient-2"></div>');
document.write('        </a>');
document.write('        <a id="w-node-471198416976-49f8c59e" href="#" class="card-item fadein-into-view change-color w-inline-block">');
document.write('          <div class="card-item-content">');
document.write('            <h4>Stay covid free or roll the dice</h4>');
document.write('          </div>');
document.write('          <div class="card-item-gradient gradient-2"></div>');
document.write('        </a>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="section section-grey"></div>');
document.write('  <div class="section section-grey">');
document.write('    <div class="container">');
document.write('      <div class="text-center">');
document.write('        <h2>Feedback ⭐️</h2>');
document.write('      </div>');
document.write('    </div>');
document.write('    <div class="slider-container">');
document.write('      <div data-delay="3000" data-animation="slide" data-autoplay="1" data-duration="300" data-infinite="1" class="slider w-slider">');
document.write('        <div class="slider-mask w-slider-mask">');
document.write('          <div class="slide w-slide">');
document.write('            <div class="feedback-card">');
document.write('              <div class="card-item">');
document.write('                <div class="card-item-content">');
document.write('                  <div class="content centered">');
document.write('                    <div class="feedback-image-holder"><img src="images/User-1.jpg" loading="lazy" alt="" class="feedback-image"></div>');
document.write('                    <p class="text-regular text-center">Found on my match and had great date! </p>');
document.write('                    <p class="feedback-author"> Lina</p>');
document.write('                  </div>');
document.write('                </div>');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="slide w-slide">');
document.write('            <div class="feedback-card">');
document.write('              <div class="card-item">');
document.write('                <div class="card-item-content">');
document.write('                  <div class="content centered">');
document.write('                    <div class="feedback-image-holder"><img src="images/User-6.jpg" loading="lazy" alt="" class="feedback-image"></div>');
document.write('                    <p class="text-regular text-center">I was worried about dating in the world of a pandemic. Crush-19 helped me stay safe and meet new people.</p>');
document.write('                    <p class="feedback-author">Katie </p>');
document.write('                  </div>');
document.write('                </div>');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div data-w-id="af3cd836-e1a3-4233-f63c-beb7bfec406e" class="slide w-slide">');
document.write('            <div class="feedback-card">');
document.write('              <div class="card-item">');
document.write('                <div class="card-item-content">');
document.write('                  <div class="content centered">');
document.write('                    <div class="feedback-image-holder"><img src="images/User-3.jpg" loading="lazy" alt="" class="feedback-image"></div>');
document.write('                    <p class="text-regular text-center">I had Covid already and I didn&#x27;t want to catch it again. This helped me match with someone who also had antibodies. </p>');
document.write('                    <p class="feedback-author">Doug </p>');
document.write('                  </div>');
document.write('                </div>');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="slide w-slide">');
document.write('            <div class="feedback-card">');
document.write('              <div class="card-item">');
document.write('                <div class="card-item-content">');
document.write('                  <div class="content centered">');
document.write('                    <div class="feedback-image-holder"><img src="images/User-4.jpg" loading="lazy" alt="" class="feedback-image"></div>');
document.write('                    <p class="text-regular text-center">I&#x27;ve been stuck in quarantine. I was able to talk with people that had my same problem. Got to Netflix and chill from a distance.</p>');
document.write('                    <p class="feedback-author">Roxie </p>');
document.write('                  </div>');
document.write('                </div>');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="slide w-slide">');
document.write('            <div class="feedback-card">');
document.write('              <div class="card-item">');
document.write('                <div class="card-item-content">');
document.write('                  <div class="content centered">');
document.write('                    <div class="feedback-image-holder"><img src="images/User-2.jpg" loading="lazy" alt="" class="feedback-image"></div>');
document.write('                    <p class="text-regular text-center">Met Mr. Right! We both love dogs so we setup a date at the local park. Our dogs sniffed butts and so did we!</p>');
document.write('                    <p class="feedback-author">Tricia</p>');
document.write('                  </div>');
document.write('                </div>');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('        <div class="slider-left-arrow w-slider-arrow-left">');
document.write('          <div class="w-icon-slider-left"></div>');
document.write('        </div>');
document.write('        <div class="slider-right-arrow w-slider-arrow-right">');
document.write('          <div class="w-icon-slider-right"></div>');
document.write('        </div>');
document.write('        <div class="slider-nav w-slider-nav w-round"></div>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="footer">');
document.write('    <div class="gradient-line"></div>');
document.write('    <div class="container w-container">');
document.write('      <div class="space-small"><img src="images/Logo-Final-1.png" loading="lazy" width="500" sizes="(max-width: 767px) 92vw, 500px" srcset="images/Logo-Final-1-p-500.png 500w, images/Logo-Final-1-p-800.png 800w, images/Logo-Final-1-p-1080.png 1080w, images/Logo-Final-1.png 3218w" alt=""></div>');
document.write('      <div class="footer-flex-container"></div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="preloader">');
document.write('    <div class="preloader-content">');
document.write('      <div class="preloader-line">');
document.write('        <div class="preloader-gradient"></div>');
document.write('      </div><img src="images/Logo-Final-1-1.png" loading="lazy" width="649" sizes="100vw" srcset="images/Logo-Final-1-1-p-500.png 500w, images/Logo-Final-1-1-p-800.png 800w, images/Logo-Final-1-1-p-1080.png 1080w, images/Logo-Final-1-1.png 3218w" alt="">');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="preloader">');
document.write('    <div class="preloader-content">');
document.write('      <div class="preloader-line">');
document.write('        <div class="preloader-gradient"></div>');
document.write('      </div><img src="images/Logo-Final-1-1.png" loading="lazy" width="649" sizes="100vw" srcset="images/Logo-Final-1-1-p-500.png 500w, images/Logo-Final-1-1-p-800.png 800w, images/Logo-Final-1-1-p-1080.png 1080w, images/Logo-Final-1-1.png 3218w" alt="">');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="preloader">');
document.write('    <div class="preloader-content">');
document.write('      <div class="preloader-line">');
document.write('        <div class="preloader-gradient"></div>');
document.write('      </div><img src="images/Logo-Final-1-1.png" loading="lazy" width="649" sizes="100vw" srcset="images/Logo-Final-1-1-p-500.png 500w, images/Logo-Final-1-1-p-800.png 800w, images/Logo-Final-1-1-p-1080.png 1080w, images/Logo-Final-1-1.png 3218w" alt="">');
document.write('    </div>');
document.write('  </div>');
document.write('  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fc7b228ac2d36009331902f" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>');
document.write('  <script src="js/covid.js" type="text/javascript"></script>');
document.write('  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->');
document.write('</body>');
document.write('</html>');
