document.write('<head>');
document.write('  <meta charset="utf-8">');
document.write('  <title>Aurora - Webflow HTML website template</title>');
document.write('  <meta content="Aurora - Webflow HTML website template" name="description">');
document.write('  <meta content="Aurora - Webflow HTML website template" property="og:title">');
document.write('  <meta content="Aurora - Webflow HTML website template" property="og:description">');
document.write('  <meta content="Aurora - Webflow HTML website template" property="twitter:title">');
document.write('  <meta content="Aurora - Webflow HTML website template" property="twitter:description">');
document.write('  <meta property="og:type" content="website">');
document.write('  <meta content="summary_large_image" name="twitter:card">');
document.write('  <meta content="width=device-width, initial-scale=1" name="viewport">');
document.write('  <meta content="Webflow" name="generator">');
document.write('  <link href="css/normalize.css" rel="stylesheet" type="text/css">');
document.write('  <link href="css/flow.css" rel="stylesheet" type="text/css">');
document.write('  <link href="css/crush19.css" rel="stylesheet" type="text/css">');
document.write('  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>');
document.write('  <script type="text/javascript">WebFont.load({  google: {    families: ["Inter:100,200,300,regular,500,600,700,800,900"]  }});</script>');
document.write('  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->');
document.write('  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>');
document.write('  <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">');
document.write('  <link href="images/webclip.png" rel="apple-touch-icon">');
document.write('</head>');
document.write('<body>');
document.write('  <div class="wrapper">');
document.write('    <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="fixed-nav w-nav">');
document.write('      <div class="container nav-container w-container">');
document.write('        <a href="index.html" class="brand w-nav-brand"><img src="images/New-Project-3.png" width="88" alt="" class="nav-logo"></a>');
document.write('        <nav role="navigation" class="nav-menu w-nav-menu">');
document.write('          <a href="login.html" class="nav-link w-inline-block">');
document.write('            <div class="nav-link-text">Login</div>');
document.write('          </a>');
document.write('          <a href="chat.html" class="nav-link w-inline-block">');
document.write('            <div class="nav-link-text">Chat</div>');
document.write('          </a>');
document.write('          <a href="parks.html" class="nav-link w-inline-block">');
document.write('            <div class="nav-link-text">Parks</div>');
document.write('          </a>');
document.write('          <a href="swipe.html" aria-current="page" class="nav-link w-inline-block w--current">');
document.write('            <div class="nav-link-text">Swipe</div>');
document.write('          </a>');
document.write('          <a href="covidstats.html" class="nav-link-2 w-nav-link">Covid Stats</a>');
document.write('        </nav>');
document.write('        <div class="menu-button w-nav-button"><img src="images/menu-icon-white.svg" loading="lazy" alt=""></div>');
document.write('      </div>');
document.write('      <div class="nav-gradient-container">');
document.write('        <div class="gradient-line thin"></div>');
document.write('      </div>');
document.write('    </div>');
document.write('    <div class="section">');
document.write('      <div class="container"></div>');
document.write('    </div>');
document.write('    <div class="footer">');
document.write('      <div class="gradient-line"></div>');
document.write('      <div class="container w-container">');
document.write('        <div class="space-small"><img src="images/Logo-Final-1.png" loading="lazy" width="500" sizes="(max-width: 767px) 92vw, 500px" srcset="images/Logo-Final-1-p-500.png 500w, images/Logo-Final-1-p-800.png 800w, images/Logo-Final-1-p-1080.png 1080w, images/Logo-Final-1.png 3218w" alt=""></div>');
document.write('        <div class="footer-flex-container"></div>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('  <div class="preloader">');
document.write('    <div class="preloader-content">');
document.write('      <div class="preloader-line">');
document.write('        <div class="preloader-gradient"></div>');
document.write('      </div><img src="images/Logo-Final-1-1.png" loading="lazy" width="649" sizes="100vw" srcset="images/Logo-Final-1-1-p-500.png 500w, images/Logo-Final-1-1-p-800.png 800w, images/Logo-Final-1-1-p-1080.png 1080w, images/Logo-Final-1-1.png 3218w" alt="">');
document.write('    </div>');
document.write('  </div>');
document.write('  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fc7b228ac2d36009331902f" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>');
document.write('  <script src="js/covid.js" type="text/javascript"></script>');
document.write('  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->');
document.write('</body>');
document.write('</html>');
